import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import { viteStaticCopy } from 'vite-plugin-static-copy';

export default defineConfig({
  server: {
    host: '127.0.0.1',
    port: 3000,
    hmr: {
        protocol: 'ws',
        host: '127.0.0.1',
    },
  },
    plugins: [
        laravel({
            input: [
                'resources/css/admin.css',
                'resources/css/guest.css',
                'resources/scss/group.scss',
                'resources/scss/shop.scss',
                'resources/scss/error.scss',
                'resources/scss/group/_pickup.scss',
                'resources/scss/group/_pickup_top.scss',
                'resources/scss/group/_eventview.scss',
                'resources/scss/admin/schedule.scss',
                'resources/scss/group/_eventdetail.scss',
                'resources/scss/shop/_eventdetail.scss',
                'resources/scss/shop/_about.scss',
                'resources/scss/shop/_fee.scss',
                'resources/scss/group/_showschedule.scss',
                'resources/scss/group/diary_top.scss',
                'resources/scss/shop/_showschedule.scss',
                'resources/scss/shop/newcomer.scss',
                'resources/scss/shop/newface.scss',
                'resources/scss/shop/castlist_top.scss',
                'resources/scss/group/pagination.scss',
                'resources/scss/shop/diarydetail.scss',
                'resources/scss/shop/diarylist.scss',
                'resources/scss/shop/newslist.scss',
                'resources/scss/shop/newsdetail.scss',
                'resources/scss/group/newstop.scss',
                'resources/scss/group/newslist.scss',
                'resources/scss/group/newsdetail.scss',
                'resources/scss/groupbase.scss',
                'resources/scss/group/front.scss',
                'resources/scss/group/pickup_top_fron.scss',
                'resources/scss/group/newface.scss',
                'resources/scss/group/banner.scss',
                'resources/scss/group/movie.scss',
                'resources/scss/group/_shop.scss',
                'resources/scss/group/_search.scss',
                'resources/scss/group/_newcomer.scss',
                'resources/scss/group/newfacelist.scss',
                'resources/scss/group/privacy.scss',
                'resources/scss/global/age.scss',
                'resources/scss/admin/work.scss',
                'resources/scss/group/today.scss',
                // 'resources/scss/group/law.scss',
                'resources/scss/group/event.scss',
                'resources/scss/shop/_today.scss',
                'resources/scss/shop/newgirls.scss',
                'resources/scss/shop/event.scss',
                'resources/scss/shop/newsdiary.scss',
                'resources/scss/shop/banner.scss',
                'resources/scss/shop/_eventview.scss',
                'resources/scss/shop/_ranking.scss',
                'resources/scss/shop/_cast.scss',
                'resources/scss/admin/sortcast.scss',
                'resources/scss/admin/casts.scss',
                'resources/scss/shop/reviewlist.scss',
                'resources/scss/mypage.scss',
                'resources/scss/shop/movielist.scss',
                'resources/scss/group/sidebar.scss',
                'resources/scss/review.scss',
                'resources/js/admin.js',
                'resources/js/group.js',
                'resources/js/shop.js',
                'resources/js/shop/profile.js',
                'resources/js/admin/event.js',
                'resources/js/admin/news.js',
                'resources/js/admin/schedule.js',
                'resources/js/admin/shopmaster.js',
                'resources/js/admin/fee.js',
                'resources/js/group/showschedule.js',
                'resources/js/shop/newGirls.js',
                'resources/js/shop/showschedule.js',
                'resources/js/group/searchResult.js',
                'resources/js/shop/castlist_top.js',
                'resources/js/shop/diarydetail.js',
                'resources/js/shop/diarylist.js',
                'resources/js/admin/sortcast.js',
                'resources/js/admin/work.js',
                'resources/js/shop/ranking.js',
            ],
            refresh: true,
        }),
        viteStaticCopy({
            targets: [
              { src: 'node_modules/tinymce/skins', dest: 'js/tinymce' },
              // { src: 'resources/fonts/*', dest: 'assets/fonts' },
              { src: 'public/assets/*', dest: 'assets' },
            ],
          }),
    ],
    assetsInclude: ['**/*.ttf', '**/*.otf', '**/*.ttc'],
    // resolve:{
    //     alias:{
    //         '@ckeditor':path.resolve(__dirname,'node_modules/@ckeditor'),
    //     },
    // },
});
