import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import { viteStaticCopy } from "vite-plugin-static-copy";

export default defineConfig({
  server: {
    host: "127.0.0.1",
    port: 3000,
    hmr: {
      protocol: "ws",
      host: "127.0.0.1",
    },
  },
  plugins: [
    laravel({
      input: [
        "resources/css/admin.css",
        "resources/css/guest.css",
        "resources/scss/group.scss",
        "resources/scss/shop.scss",
        "resources/scss/error.scss",
        "resources/scss/group/_pickup.scss",
        "resources/scss/group/_pickup_top.scss",
        "resources/scss/group/_eventview.scss",
        "resources/scss/admin/schedule.scss",
        "resources/scss/group/_eventdetail.scss",
        "resources/scss/shop/_eventdetail.scss",
        "resources/scss/shop/_about.scss",
        "resources/scss/shop/_fee.scss",
        "resources/scss/group/_showschedule.scss",
        "resources/scss/group/diary_top.scss",
        "resources/scss/shop/_showschedule.scss",
        "resources/scss/shop/newcomer.scss",
        "resources/scss/shop/newface.scss",
        "resources/scss/shop/castlist_top.scss",
        "resources/scss/group/pagination.scss",
        "resources/scss/shop/diarydetail.scss",
        "resources/scss/shop/diarylist.scss",
        "resources/scss/shop/newslist.scss",
        "resources/scss/shop/newsdetail.scss",
        "resources/scss/group/newstop.scss",
        "resources/scss/group/newslist.scss",
        "resources/scss/group/newsdetail.scss",
        "resources/scss/groupbase.scss",
        "resources/scss/group/front.scss",
        "resources/scss/group/pickup_top_fron.scss",
        "resources/scss/group/newface.scss",
        "resources/scss/group/banner.scss",
        "resources/scss/group/movie.scss",
        "resources/scss/group/_shop.scss",
        "resources/scss/group/_search.scss",
        "resources/scss/group/_newcomer.scss",
        "resources/scss/group/newfacelist.scss",
        "resources/scss/group/privacy.scss",
        "resources/scss/global/age.scss",
        "resources/scss/admin/work.scss",
        "resources/scss/group/today.scss",
        // 'resources/scss/group/law.scss',
        "resources/scss/group/event.scss",
        "resources/scss/shop/_today.scss",
        "resources/scss/shop/newgirls.scss",
        "resources/scss/shop/event.scss",
        "resources/scss/shop/newsdiary.scss",
        "resources/scss/shop/banner.scss",
        "resources/scss/shop/_eventview.scss",
        "resources/scss/shop/_ranking.scss",
        "resources/scss/shop/_cast.scss",
        "resources/scss/shops/shizuku/home.scss",
        "resources/scss/admin/sortcast.scss",
        "resources/scss/admin/casts.scss",
        "resources/scss/shop/reviewlist.scss",
        "resources/scss/mypage.scss",
        "resources/scss/shop/movielist.scss",
        "resources/scss/group/sidebar.scss",
        "resources/scss/review.scss",
        "resources/scss/member.scss",
        "resources/scss/password.scss",
        "resources/js/admin.js",
        "resources/js/group.js",
        "resources/js/shop.js",
        "resources/js/shop/profile.js",
        "resources/js/admin/event.js",
        "resources/js/admin/news.js",
        "resources/js/admin/schedule.js",
        "resources/js/admin/shopmaster.js",
        "resources/js/admin/fee.js",
        "resources/js/group/showschedule.js",
        "resources/js/shop/newGirls.js",
        "resources/js/shop/showschedule.js",
        "resources/js/group/searchResult.js",
        "resources/js/shop/castlist_top.js",
        "resources/js/shop/diarydetail.js",
        "resources/js/shop/diarylist.js",
        "resources/js/admin/sortcast.js",
        "resources/js/admin/work.js",
        "resources/js/shop/ranking.js",

        "resources/scss/app.scss",
        "resources/scss/shops/shizuku/home.scss",
        "resources/scss/shops/pussycat/home.scss",
        "resources/js/shops/shizuku/home.js",
        "resources/js/shops/home-header.js",
        "resources/js/shops/news-section.js",
        "resources/js/shops/new-girl-slider.js",
        "resources/js/shops/castlist-slider.js",
        "resources/scss/shops/shizuku/profile.scss",
        "resources/scss/shops/pussycat/profile.scss",

        "resources/scss/shops/contact-info.scss",
        "resources/scss/shops/home-header.scss",
        "resources/js/shops/home-header.js",
        "resources/js/shops/shizuku/profile.js",
        "resources/scss/shops/shizuku/castlist.scss",
        "resources/scss/shops/pussycat/castlist.scss",
        "resources/scss/shops/pussycat/component/contact-info.scss",
        "resources/scss/shops/home-header.scss",
        "resources/js/shops/home-header.js",
        "resources/scss/shops/shizuku/schedule.scss",
        "resources/scss/shops/shizuku/page-layout.scss",
        "resources/scss/shops/footer.scss",
        "resources/scss/shops/fixed-phone-button.scss",
        "resources/scss/shops/fixed-side-buttons.scss",
        "resources/scss/shops/menu-overlay.scss",
        "resources/scss/shops/shizuku/newcast.scss",
        "resources/scss/shops/news-card.scss",
        "resources/scss/shops/shizuku/news.scss",
        "resources/scss/shops/shizuku/news-detail.scss",
        "resources/scss/shops/shizuku/photo-diary.scss",
        "resources/scss/shops/event-card.scss",
        "resources/scss/shops/shizuku/event.scss",
        "resources/scss/shops/shizuku/event-detail.scss",
        "resources/js/shops/shizuku/photo-diary.js",
        "resources/scss/shops/shizuku/shop-list.scss",
        "resources/scss/shops/shizuku/system.scss",
        "resources/scss/shops/review-card.scss",
        "resources/scss/shops/shizuku/ranking.scss",
        "resources/scss/shops/shizuku/review.scss",
        "resources/js/shops/shizuku/ranking.js",
        // "resources/scss/shops/pagination.scss",
        'resources/js/shops/event-section.js',
        'resources/scss/shops/shizuku/movie.scss',
        'resources/scss/shops/shizuku/photo-diary-detail.scss',
        'resources/js/shops/shizuku/photo-diary-detail.js',
        'resources/scss/shops/shizuku/access.scss',

        'resources/scss/shops/pussycat/page-layout.scss',
        'resources/scss/shops/pussycat/component/home-header.scss',
        'resources/scss/shops/pussycat/component/footer.scss',
        'resources/scss/shops/pussycat/component/fixed-phone-button.scss',
        'resources/scss/shops/pussycat/component/fixed-side-buttons.scss',
        'resources/scss/shops/pussycat/component/menu-overlay.scss',
        'resources/scss/shops/pussycat/schedule.scss',
        'resources/scss/shops/pussycat/system.scss',
        'resources/scss/shops/pussycat/newcast.scss',
        'resources/scss/shops/pussycat/component/news-card.scss',
        'resources/scss/shops/pussycat/component/event-card.scss',
        'resources/scss/shops/pussycat/photo-diary.scss',
        'resources/scss/shops/pussycat/review.scss',
        'resources/scss/shops/pussycat/component/review-card.scss',
        'resources/scss/shops/pussycat/ranking.scss',
        'resources/scss/shops/pussycat/access.scss',
        'resources/scss/shops/pussycat/shop-list.scss',
        'resources/scss/shops/pussycat/movie.scss',
        'resources/scss/shops/pussycat/news.scss',
        'resources/scss/shops/pussycat/event.scss',
        'resources/js/shops/pussycat/photo-diary.js',
        'resources/scss/shops/pussycat/news-detail.scss',
        'resources/scss/shops/pussycat/event-detail.scss',
        'resources/scss/shops/pussycat/photo-diary-detail.scss',
        'resources/js/shops/pussycat/photo-diary-detail.js',


        'resources/scss/shops/miyabi/home.scss',
        'resources/scss/shops/miyabi/page-layout.scss',
        'resources/scss/shops/miyabi/component/home-header.scss',
        'resources/scss/shops/miyabi/component/footer.scss',
        'resources/scss/shops/miyabi/component/fixed-phone-button.scss',
        'resources/scss/shops/miyabi/component/fixed-side-buttons.scss',
        'resources/scss/shops/miyabi/component/menu-overlay.scss',
        'resources/scss/shops/miyabi/schedule.scss',
        'resources/scss/shops/miyabi/system.scss',
        'resources/scss/shops/miyabi/newcast.scss',
        'resources/scss/shops/miyabi/component/news-card.scss',
        'resources/scss/shops/miyabi/component/event-card.scss',
        'resources/scss/shops/miyabi/photo-diary.scss',
        'resources/scss/shops/miyabi/review.scss',
        'resources/scss/shops/miyabi/component/review-card.scss',
        'resources/scss/shops/miyabi/ranking.scss',
        'resources/scss/shops/miyabi/access.scss',
        'resources/scss/shops/miyabi/shop-list.scss',
        'resources/scss/shops/miyabi/movie.scss',
        'resources/scss/shops/miyabi/news.scss',
        'resources/scss/shops/miyabi/event.scss',
        'resources/js/shops/miyabi/photo-diary.js',
        'resources/scss/shops/miyabi/news-detail.scss',
        'resources/scss/shops/miyabi/event-detail.scss',
        'resources/scss/shops/miyabi/photo-diary-detail.scss',
        'resources/js/shops/miyabi/photo-diary-detail.js',
        'resources/scss/shops/miyabi/castlist.scss',
        'resources/scss/shops/miyabi/profile.scss',

        'resources/scss/shops/siroganeze/home.scss',
        'resources/scss/shops/siroganeze/page-layout.scss',
        'resources/scss/shops/siroganeze/component/home-header.scss',
        'resources/scss/shops/siroganeze/component/footer.scss',
        'resources/scss/shops/siroganeze/component/fixed-phone-button.scss',
        'resources/scss/shops/siroganeze/component/fixed-side-buttons.scss',
        'resources/scss/shops/siroganeze/component/menu-overlay.scss',
        'resources/scss/shops/siroganeze/schedule.scss',
        'resources/scss/shops/siroganeze/system.scss',
        'resources/scss/shops/siroganeze/newcast.scss',
        'resources/scss/shops/siroganeze/component/news-card.scss',
        'resources/scss/shops/siroganeze/component/event-card.scss',
        'resources/scss/shops/siroganeze/photo-diary.scss',
        'resources/scss/shops/siroganeze/review.scss',
        'resources/scss/shops/siroganeze/component/review-card.scss',
        'resources/scss/shops/siroganeze/ranking.scss',
        'resources/scss/shops/siroganeze/access.scss',
        'resources/scss/shops/siroganeze/shop-list.scss',
        'resources/scss/shops/siroganeze/movie.scss',
        'resources/scss/shops/siroganeze/news.scss',
        'resources/scss/shops/siroganeze/event.scss',
        'resources/js/shops/siroganeze/photo-diary.js',
        'resources/scss/shops/siroganeze/news-detail.scss',
        'resources/scss/shops/siroganeze/event-detail.scss',
        'resources/scss/shops/siroganeze/photo-diary-detail.scss',
        'resources/scss/shops/siroganeze/castlist.scss',
        'resources/js/shops/siroganeze/photo-diary-detail.js',
        'resources/scss/shops/siroganeze/profile.scss',

        'resources/scss/shops/en/home.scss',
        'resources/scss/shops/en/page-layout.scss',
        'resources/scss/shops/en/component/home-header.scss',
        'resources/scss/shops/en/component/footer.scss',
        'resources/scss/shops/en/component/fixed-phone-button.scss',
        'resources/scss/shops/en/component/fixed-side-buttons.scss',
        'resources/scss/shops/en/component/menu-overlay.scss',
        'resources/scss/shops/en/schedule.scss',
        'resources/scss/shops/en/system.scss',
        'resources/scss/shops/en/newcast.scss',
        'resources/scss/shops/en/component/news-card.scss',
        'resources/scss/shops/en/component/event-card.scss',
        'resources/scss/shops/en/photo-diary.scss',
        'resources/scss/shops/en/review.scss',
        'resources/scss/shops/en/component/review-card.scss',
        'resources/scss/shops/en/ranking.scss',
        'resources/scss/shops/en/access.scss',
        'resources/scss/shops/en/shop-list.scss',
        'resources/scss/shops/en/movie.scss',
        'resources/scss/shops/en/news.scss',
        'resources/scss/shops/en/event.scss',
        'resources/js/shops/en/photo-diary.js',
        'resources/scss/shops/en/news-detail.scss',
        'resources/scss/shops/en/event-detail.scss',
        'resources/scss/shops/en/photo-diary-detail.scss',
        'resources/scss/shops/en/castlist.scss',
        'resources/js/shops/en/photo-diary-detail.js',
        'resources/scss/shops/en/profile.scss',
        'resources/js/shops/en/home.js',

        'resources/scss/shops/lovestory/home.scss',
        'resources/scss/shops/lovestory/page-layout.scss',
        'resources/scss/shops/lovestory/component/home-header.scss',
        'resources/scss/shops/lovestory/component/footer.scss',
        'resources/scss/shops/lovestory/component/fixed-phone-button.scss',
        'resources/scss/shops/lovestory/component/fixed-side-buttons.scss',
        'resources/scss/shops/lovestory/component/menu-overlay.scss',
        'resources/scss/shops/lovestory/schedule.scss',
        'resources/scss/shops/lovestory/system.scss',
        'resources/scss/shops/lovestory/newcast.scss',
        'resources/scss/shops/lovestory/component/news-card.scss',
        'resources/scss/shops/lovestory/component/event-card.scss',
        'resources/scss/shops/lovestory/photo-diary.scss',
        'resources/scss/shops/lovestory/review.scss',
        'resources/scss/shops/lovestory/component/review-card.scss',
        'resources/scss/shops/lovestory/ranking.scss',
        'resources/scss/shops/lovestory/access.scss',
        'resources/scss/shops/lovestory/shop-list.scss',
        'resources/scss/shops/lovestory/movie.scss',
        'resources/scss/shops/lovestory/news.scss',
        'resources/scss/shops/lovestory/event.scss',
        'resources/js/shops/lovestory/photo-diary.js',
        'resources/scss/shops/lovestory/news-detail.scss',
        'resources/scss/shops/lovestory/event-detail.scss',
        'resources/scss/shops/lovestory/photo-diary-detail.scss',
        'resources/scss/shops/lovestory/castlist.scss',
        'resources/js/shops/lovestory/photo-diary-detail.js',
        'resources/scss/shops/lovestory/profile.scss',

        'resources/scss/groups.scss',
        'resources/js/groups.js',
        'resources/scss/groups/section-title.scss',
        'resources/scss/groups/schedule-content.scss',
        'resources/scss/groups/event-content.scss',
        'resources/scss/groups/newface-content.scss',
        'resources/scss/groups/pickup-content.scss',
        'resources/scss/groups/diary-content.scss',
        'resources/scss/groups/movie-content.scss',

        'resources/scss/groups/header-sub.scss',
        'resources/scss/groups/banner.scss',
        'resources/scss/groups/photodiary.scss',
        'resources/js/groups/photodiary.js',
        'resources/scss/groups/newface-card.scss',
        'resources/scss/groups/newface-page.scss',
        'resources/scss/groups/schedule.scss',
        'resources/scss/groups/schedule-card.scss',
        'resources/scss/groups/event-card.scss',
        'resources/scss/groups/event.scss',
        'resources/scss/groups/event-detail.scss',
        'resources/scss/groups/shop.scss',
        'resources/scss/groups/movie.scss',
        'resources/scss/groups/girl-search.scss'
      ],
      refresh: true,
    }),
    viteStaticCopy({
      targets: [
        { src: "node_modules/tinymce/skins", dest: "js/tinymce" },
        // { src: 'resources/fonts/*', dest: 'assets/fonts' },
        { src: "public/assets/*", dest: "assets" },
      ],
    }),
  ],
  assetsInclude: ["**/*.ttf", "**/*.otf", "**/*.ttc"],
  // resolve:{
  //     alias:{
  //         '@ckeditor':path.resolve(__dirname,'node_modules/@ckeditor'),
  //     },
  // },
});
