name: Deploy to Sakura FTP

on:
  push:
    branches:
      - test-front   # dev1ブランチにpushされた時だけ実行

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload to FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_TEST_SERVER }}
          username: ${{ secrets.FTP_TEST_USERNAME }}
          password: ${{ secrets.FTP_TEST_PASSWORD }}
          server-dir: ${{ secrets.FTP_TEST_PATH }}
          local-dir: ./   # アップロード対象。必要に応じて public/ や build/ に変更可能
          method: ftps
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/tests/**
